const exams=[
['Ácido úrico','$3,30'],['Albúmina','$3,30'],['Amilasa','$4,00'],['Aglutinaciones febriles','$7,00'],['ASTO - Antiestreptolisina','$8,80'],['Alfa feto proteínas - AFP','$13,28'],['Ácido fólico','$13,00'],['ACTIN F. IgA / ACTIN','$28,60'],['ACTIN IgG','$28,60'],['ANCA C-P','$40,00'],['ASCA IgG','$25,50'],['ASCA IgA','$25,50'],['Antitrombina','$39,61'],['Apolipoproteína A1','$15,40'],['Apolipoproteína B','$9,36'],['BUN (incluye urea)','$6,09'],['Creatinina','$3,30'],['Colesterol total','$3,30'],['Colesterol HDL','$5,50'],['Colesterol LDL','$5,60'],['Coprocultivo (heces)','$22,00'],['Calcio','$4,00'],['CA 125 (ovario, útero)','$15,40'],['Ceruloplasmina','$35,07'],['Calprotectina','$36,40'],['Calcio iónico','$8,00'],['Cloro','$3,38'],['Cardiolipina IgG','$24,44'],['Cardiolipina IgM','$24,44'],['CK MB-CPK','$13,52'],['Creatinina (orina)','$6,09'],['Colinesterasa','$4,40'],['Interleukina 6','$34,00'],['Insulina plasmática en ayunas','$14,30'],['IgG por nefelometría','$16,00'],['IgM por nefelometría','$17,00'],['IgA por nefelometría','$17,00'],['IgE total','$16,00'],['Influenza A/B/H1N1 por PCR GeneXpert','$188,37'],['Influenza A/B antígeno','$28,00'],['Insulina 2h post prandial','$34,00'],['KOH','$13,20'],['Kappa (orina)','$27,63'],['Kappa 24h','$28,60'],['Lipasa','$4,40'],['LDH (deshidrogenasa láctica)','$4,40'],['Linfocitos B (CD19-CD20)','$80,00'],['Linfocitos NK (CD16-CD56)','$48,30'],['Lipoproteína A','$16,00'],['Litio','$16,00'],['Lactoferrina','$20,00'],['Norovirus','$40,00'],['Osmolalidad','$14,49'],['Osteocalcina','$50,72'],['Oxalato urinario','$46,20'],['Opiáceos cuantitativa','$11,59'],['Plaquetas','$6,00'],['Prueba de Coombs directa','$9,00'],['Prueba de Coombs indirecta','$9,00'],['Parasitoscópico concentración (heces)','$6,00'],['PSA total','$16,93'],['PSA libre','$25,30'],['Potasio','$4,00'],['Pro-BNP','$65,00'],['Procalcitonina','$74,38'],['Prealbúmina','$30,00'],['Prolactina','$12,00'],['Progesterona','$12,00'],['Rotavirus','$13,00'],['R. de Widal y Weill Felix','$7,00'],['Factor reumatoideo por nefelometría','$16,00'],['RPR','$5,00'],['Rubeola IgG','$16,72'],['Rubeola IgM','$16,72'],['Sangre oculta - HB humana','$7,10'],['Sodio','$4,00'],['Sodio (orina)','$4,00'],['Strept-A','$13,20'],['Salmonella antígeno','$14,00'],['Urea','$3,30'],['Urocultivo (orina)','$18,00'],['Urea 24h','$6,30'],['V.D.R.L.','$5,50'],['Vitamina B12','$13,00'],['VLDL colesterol','$6,30'],['V.D.R.L. cuantitativo','$9,00'],['Varicela zóster IgG','$28,00'],['Varicela zóster IgM','$21,25'],['Vitamina D total','$32,00'],['Vitamina E','$65,10'],['Virus sincitial respiratorio','$36,75'],['Ziehl Neelsen','$7,20'],['Zinc','$35,00'],['Zika virus IgG','$100,49'],['Zika virus IgM','$75,74']
].map(([name,price])=>({name,price}));


const notes=[
{title:'El estrés: Un enemigo silencioso que afecta nuestra salud física y mental',date:'07 Nov 2024',tag:'SALUD',body:'La Organización Mundial de la Salud (OMS) define el estrés como cualquier tipo de cambio que provoca agotamiento físico, emocional o psicológico. LABS publicó esta nota como contenido de orientación para pacientes.'},
{title:'Hígado, el «filtro» natural del cuerpo',date:'05 Sep 2024',tag:'HÍGADO · LABS',body:'Mantenerlo sano a través de una buena alimentación es vital. LABS explica el papel del hígado en la actividad metabólica, la producción de bilis, el procesamiento de la sangre y el almacenamiento de nutrientes. También aborda la insuficiencia hepática y la prueba de función hepática.'},
{title:'Riñones: los héroes ocultos de nuestro cuerpo',date:'23 Jul 2024',tag:'EXÁMENES · SALUD',body:'LABS aborda el cuidado de los riñones y destaca la importancia de la hidratación, el ejercicio y una alimentación baja en sal.'},
{title:'4 síntomas que debes saber sobre el dengue',date:'05 Mar 2024',tag:'SALUD',body:'Nota de salud publicada por LABS sobre síntomas que deben conocerse en relación con el dengue.'},
{title:'Perdiendo peso, ¿qué exámenes de laboratorio necesito?',date:'05 Feb 2024',tag:'EXÁMENES · SALUD',body:'Contenido de LABS sobre los exámenes de laboratorio que pueden formar parte de la evaluación relacionada con la pérdida de peso.'},
{title:'7 exámenes básicos que debes realizarte en el año',date:'19 Jan 2024',tag:'EXÁMENES · SALUD',body:'Contenido educativo de LABS sobre exámenes básicos de laboratorio y su utilidad como parte del cuidado de la salud.'},
{title:'¿Cómo los exámenes revelan el impacto del estrés en tu salud?',date:'11 Jan 2024',tag:'EXÁMENES · SALUD',body:'LABS explica la relación entre el estrés y la información que pueden aportar determinados exámenes de laboratorio.'},
{title:'Cáncer de mama, la tercera causa de muerte en mujeres',date:'18 Oct 2023',tag:'SALUD',body:'Contenido de salud publicado por LABS sobre cáncer de mama.'},
{title:'Intolerancias vs. comportamientos, ¿qué relación existe?',date:'06 Oct 2023',tag:'SALUD',body:'Nota publicada por LABS sobre intolerancias y comportamientos relacionados con la salud.'},
{title:'Exámenes para detectar hígado graso',date:'08 Sep 2023',tag:'LABS · SALUD',body:'Contenido de LABS sobre pruebas de laboratorio relacionadas con la detección de hígado graso.'},
{title:'¿Mareos y dolor de cabeza? Puedes ser hígado graso.',date:'01 Sep 2023',tag:'LABS · SALUD',body:'Nota publicada por LABS sobre síntomas y su posible relación con el hígado graso.'},
{title:'Virus sincitial, el camaleón de un resfriado común',date:'01 Jul 2022',tag:'SALUD',body:'Contenido educativo de LABS sobre el virus sincitial.'},
{title:'¿Cómo prevenir enfermedades del riñón con exámenes rutinarios?',date:'28 Mar 2022',tag:'LABS',body:'LABS aborda la prevención y el valor de los exámenes rutinarios relacionados con la salud renal.'}
];

const locations={
  guayaquil:{city:'Guayaquil',label:'Sede principal',address:'Av. Abel Romeo Castillo y Juan Tanca Marengo, Torre Médica 2, piso 4, consultorios 417 y 418.',hours:'LUN–VIE 06h30–18h00 · SAB 06h30–12h00'},
  quito:{city:'Quito',address:'Av. Mariana de Jesús OE7-02 y Nuño de Valderrama. Edificio CITIMED, Planta Baja Local 7.',hours:'LUN–VIE 07h00–16h00'},
  manta:{city:'Manta',address:'Edificio Umiñamed, planta baja (misma sede de EndoscopyNet Manta).',hours:'LUN–VIE 07h00–15h40'},
  'santo-domingo':{city:'Santo Domingo',address:'Av. Quito, entre Latacunga e Ibarra.',hours:'LUN–VIE 07h30–16h10'},
  milagro:{city:'Milagro',address:'Calle 17 de Septiembre, entre Calle Esmeraldas y Guayas, frente a CNEL.',hours:'LUN–VIE 08h00–16h00'}
};

const nav=document.querySelector('#mainNav');
const menu=document.querySelector('.menubtn');
menu?.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',open)});
document.querySelectorAll('#mainNav a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu?.setAttribute('aria-expanded','false')}));

const examGrid=document.querySelector('#examGrid'), search=document.querySelector('#examSearch'), count=document.querySelector('#examCount');
function renderExams(term=''){const q=term.trim().toLowerCase();const list=exams.filter(x=>x.name.toLowerCase().includes(q));count.textContent=`${list.length} examen${list.length===1?'':'es'} disponible${list.length===1?'':'s'}`;examGrid.innerHTML=list.map((x,i)=>`<button class="exam" type="button" data-exam="${i}"><strong>${x.name}</strong><em>${x.price}</em></button>`).join('')||'<div class="exam"><strong>No encontramos ese examen.</strong><em>—</em></div>'}
renderExams(); search?.addEventListener('input',e=>renderExams(e.target.value)); document.querySelector('#clearSearch')?.addEventListener('click',()=>{search.value='';renderExams()});
examGrid?.addEventListener('click',e=>{const card=e.target.closest('[data-exam]');if(!card)return;selected.add(+card.dataset.exam);renderQuote();modal.classList.add('show');modal.setAttribute('aria-hidden','false')});

const tabs=document.querySelector('#locationTabs'),detail=document.querySelector('#locationDetail');
const locationKeys=Object.keys(locations);
function showLocation(key){const x=locations[key];tabs.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.key===key));detail.innerHTML=`<h4>${x.city}</h4><p>${x.address}</p><div class="hours"><b>Horario</b><br>${x.hours}</div><p><a href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(x.address)}" target="_blank" rel="noopener">Ver ubicación en Google Maps →</a></p>`}
tabs.innerHTML=locationKeys.map(k=>`<button type="button" data-key="${k}">${locations[k].city}</button>`).join('');tabs.addEventListener('click',e=>{const b=e.target.closest('button');if(b)showLocation(b.dataset.key)});showLocation('guayaquil');

const noteGrid=document.querySelector('#noteGrid'), noteModal=document.querySelector('#noteModal');
noteGrid.innerHTML=notes.slice(0,6).map((n,i)=>`<button class="noteCard" type="button" data-note="${i}"><small>${n.date} · ${n.tag}</small><h3>${n.title}</h3><span>Leer nota →</span></button>`).join('');
function openNote(i){const n=notes[i];document.querySelector('#noteModalTitle').textContent=n.title;document.querySelector('#noteModalDate').textContent=n.date+' · '+n.tag;document.querySelector('#noteModalBody').textContent=n.body;noteModal.classList.add('show');noteModal.setAttribute('aria-hidden','false')}
noteGrid.addEventListener('click',e=>{const b=e.target.closest('[data-note]');if(b)openNote(+b.dataset.note)});
document.querySelector('#closeNote')?.addEventListener('click',()=>{noteModal.classList.remove('show');noteModal.setAttribute('aria-hidden','true')});

const modal=document.querySelector('#quoteModal'),items=document.querySelector('#quoteItems'),totalEl=document.querySelector('#quoteTotal');
let selected=new Set();
function renderQuote(){items.innerHTML=exams.map((x,i)=>`<label class="quoteItem"><input type="checkbox" data-i="${i}" ${selected.has(i)?'checked':''}> <span>${x.name}<br><b>${x.price}</b></span></label>`).join('');items.querySelectorAll('input').forEach(c=>c.addEventListener('change',e=>{const i=+e.target.dataset.i;e.target.checked?selected.add(i):selected.delete(i);updateTotal()}));updateTotal()}
function updateTotal(){const sum=[...selected].reduce((a,i)=>a+Number(exams[i].price.replace('$','').replace(',','.')),0);totalEl.textContent=`$${sum.toFixed(2).replace('.',',')}`}
document.querySelector('#openQuote')?.addEventListener('click',()=>{modal.classList.add('show');modal.setAttribute('aria-hidden','false');renderQuote()});document.querySelector('#closeQuote')?.addEventListener('click',()=>{modal.classList.remove('show');modal.setAttribute('aria-hidden','true')});
document.querySelectorAll('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m){m.classList.remove('show');m.setAttribute('aria-hidden','true')}}));
document.querySelector('#quoteForm')?.addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.target);const names=[...selected].map(i=>exams[i].name).join(', ');document.querySelector('#quoteMsg').textContent=selected.size?`Solicitud preparada para ${data.get('name')}. Exámenes: ${names}. Total estimado: ${totalEl.textContent}. Para envío real, conecta este formulario con el backend de LABS.`:'Selecciona al menos un examen antes de continuar.'});

const translations={
es:{navHome:'Inicio',navAbout:'Nosotros',navNotes:'Notas de salud',navContact:'Contacto',results:'Resultados ↗',heroEyebrow:'DIAGNÓSTICO CLÍNICO · ECUADOR',heroTitle:'Resultados que ayudan a cuidar lo que más importa.',heroLead:'Servicios de laboratorio clínico confiables, oportunos y orientados a apoyar las decisiones médicas y el bienestar de nuestros pacientes.',quoteExam:'Cotizar exámenes',findLocation:'Encontrar una sede',aboutTitle:'Su laboratorio de confianza.',quoteTitle:'Consulta y cotiza tus exámenes.',quoteIntro:'Un solo punto para buscar, revisar y seleccionar los exámenes disponibles.',quoteSelected:'Cotizar exámenes seleccionados →',notesTitle:'Información de salud publicada por LABS.',notesIntro:'Contenido educativo publicado por LABS para pacientes y familias.',contactTitle:'Estamos para ayudarte.'},
en:{navHome:'Home',navAbout:'About us',navNotes:'Health notes',navContact:'Contact',results:'Results ↗',heroEyebrow:'CLINICAL DIAGNOSTICS · ECUADOR',heroTitle:'Results that help care for what matters most.',heroLead:'Reliable and timely clinical laboratory services designed to support medical decisions and patient wellbeing.',quoteExam:'Quote tests',findLocation:'Find a location',aboutTitle:'Your trusted laboratory.',quoteTitle:'Search and quote your tests.',quoteIntro:'One place to search, review and select available tests.',quoteSelected:'Quote selected tests →',notesTitle:'Health information published by LABS.',notesIntro:'Educational content published by LABS for patients and families.',contactTitle:'We are here to help.'}
};
function setLanguage(lang){currentLang=lang;document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(translations[lang][k])el.textContent=translations[lang][k]});document.querySelectorAll('#languageToggle,#footerLanguage').forEach(b=>b.textContent=lang==='es'?'ES | EN':'EN | ES');localStorage.setItem('labs-language',lang)}
let currentLang=localStorage.getItem('labs-language')||'es';
document.querySelector('#languageToggle')?.addEventListener('click',()=>setLanguage(currentLang==='es'?'en':'es'));
document.querySelector('#footerLanguage')?.addEventListener('click',()=>setLanguage(currentLang==='es'?'en':'es'));
setLanguage(currentLang);
